# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sellerapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_27923f020ec049b6a4b19bd48a281c36 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_93cc8250a8b64a0cb1d4699fc0b447d9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_27923f020ec049b6a4b19bd48a281c36 }}/karads007@gmail.com/sellerapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sellerapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_11da16d3b04c413884871d449af0b278 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_27923f020ec049b6a4b19bd48a281c36 }}/karads007@gmail.com/sellerapi:${{ github.sha }}'